config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  resources :timers
  resources :timer_titles do
    resources :timer_count
  end
  root to:'timers#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/time_count.rb
class TimeCount < ApplicationRecord
  belongs_to :timer_title
end

app/models/timer_title.rb
class TimerTitle < ApplicationRecord
  belongs_to :user
  has_many :time_counts, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :timer_titles, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name])
  end
end

app/controllers/timer_count_controller.rb
class TimerCountController < ApplicationController
  def new
    @timer_title = TimerTitle.find(params[:timer_title_id])
    @timer_count = TimeCount.new
    @history = TimeCount.where(timer_title_id: params[:timer_title_id])
    time_calc(@history)
  end
  def create
    @timer_title = TimerTitle.find(params[:timer_title_id])
    @timer_count = TimeCount.create(params_timer_count)
    redirect_to timer_path(current_user.id)
  end

  private
  def params_timer_count
    params.permit(:time).merge(timer_title_id: @timer_title.id)
  end
  def time_calc(history)
    @history_time = []
    history.each do |history|
      hour = (history.time/(60*60)).floor.to_s
      history.time %= 60*60
      min = ("0" + (history.time/(60)).floor.to_s).slice(-2,2)
      history.time %= 60
      sec = ("0" + history.time.floor.to_s).slice(-2,2)
      timer = hour +":"+min+":"+sec
      @history_time.push(timer)
    end
  end
end

app/controllers/timer_titles_controller.rb
class TimerTitlesController < ApplicationController
  def new
    @timer_title = TimerTitle.new
  end
  def create
    @timer_title = TimerTitle.new(params_timer_title)
    if @timer_title.save
      redirect_to timer_path(current_user.id)
    else
      render :new
    end
  end
  def destroy
    @timer_title = TimerTitle.find(params[:id])
    @timer_title.destroy
    redirect_to timer_path(current_user.id)
  end

  private

  def params_timer_title
    params.require(:timer_title).permit(:timer_title).merge(user_id: current_user.id)
  end
end

app/controllers/timers_controller.rb
class TimersController < ApplicationController
  def index
  end
  def show
    @timer_title = TimerTitle.where(user_id: current_user.id)
    time_calc(@timer_title)
  end
  private

  def time_calc(timer_title)
    @time_count = []
    timer_title.each do |timer_title|
      if time_count_id =TimeCount.where(timer_title_id: timer_title.id).exists?
        time_count_id =TimeCount.where(timer_title_id: timer_title.id) 
        time_count = time_count_id.sum(:time)
        hour = (time_count/(60*60)).floor.to_s
        time_count %= 60*60
        min = ("0" + (time_count/(60)).floor.to_s).slice(-2,2)
        time_count %= 60
        sec = ("0" + time_count.floor.to_s).slice(-2,2)
        timer = hour +":"+min+":"+sec
        @time_count.push(timer)
      else
        @time_count.push("0:00:00")
      end
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/timer_count_helper.rb
module TimerCountHelper
end

app/helpers/timer_titles_helper.rb
module TimerTitlesHelper
end

app/helpers/timers_helper.rb
module TimersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TimerApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width,initial-scale=1.0,minimum-scale=1.0">
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/shared/_footer.html.erb
<div class="footer">
  <p>-- footer --</p>
</div>

app/views/shared/_header.html.erb
<div class="header">
  <div class="header-right">
    <div class="app_title">
    <%= link_to "timer", root_path , class:"title"%>
    </div>
  </div>
  <div class="header-left">
    <% if user_signed_in?%>
    <div class="devise-contents">
    <%= link_to "ログアウト", destroy_user_session_path, class:"devise",method: :delete%>
    </div>
    <div class="devise-contents">
    <%= link_to "マイページ", timer_path(current_user.id), class:"devise" %>
    </div>
    <%else%>
    <div class="devise-contents">
    <%= link_to "新規登録", new_user_registration_path, class:"devise"%>
    </div>
    <div class="devise-contents">
    <%= link_to "ログイン", new_user_session_path, class:"devise"%>
    </div>
    <%end%>
  </div>
</div>

app/views/timer_count/new.html.erb
<%= render "shared/header" %>
<div class="main">
  <div class="timer-count-new">
    <h1 class="timer-count-new-title"><%= @timer_title.timer_title%></h1>
    <h1 class="timer" id="timer"> 0:00:00</h1>
    <div class="bottons">
      <button class='botton' id="start">開始/再開</button>
      <button class='botton' id="stop">一時停止</button>
    </div>
    <div class="timer-count-new-forms">
      <%= form_with url:timer_title_timer_count_index_path(@timer_title.id), local: true do |f| %>
      <%= f.text_field :time ,id:"timer-count-new-form", class:"hidden"%>
      <%= f.submit "保存する",class:"botton" %>
      <%end%>
    </div>
  </div>
  <div class="history">
    <h1 class="history-title">履歴</h1>
    <div class="history-table">
      <div class="daytimes">
      <h1>日時</h1>
      </div>
      <div class="times">
      <h1>時間</h1>
      </div>
    </div>
      <% if @history.exists?%>
        <%@history.zip(@history_time) do |history, history_time|%>
        <div class="history-table">
          <div class="daytimes">
          <h1><%=l history.created_at,format: :short%></h1>
          </div>
          <div class="times">
          <h1><%=history_time%></h1>
          </div>
        </div>
        <%end%>
      <%end%>
  </div>
</div>
<%= render "shared/footer" %>

app/views/timer_titles/new.html.erb
<%= render "shared/header" %>
<div class="main">
  <div class="timer-title-new">
  <h1 class="timer-title-new-title">タイマー作成</h1>
    <%= form_with(model: @timer_title, local: true) do |f| %>
      <%= f.text_field :timer_title ,class:"timer-title-new-form",  maxlength:"10"%>
    <%= f.submit "作成する",class:"timer-title-new-btn" %>
  <%end%>
  </div>
</div>
<%= render "shared/footer" %>

app/views/timers/index.html.erb
<%= render "shared/header" %>
<div class="main">
<div class="messages">
  <h1 class="main-message">自分の努力の時間を計ろう！！</h1>
  <div class="message-contents">
  <h1 class="how-to-use"> 〜使用方法〜</h1>
  <p class="message">①マイページに行ってタイマーを作ろう</p>
  <p class="message">②タイマーを作ったら時間を計ろう！！</p>
  <p class="message">③目指せ１万時間！！</p>
  </div>
</div>
</div>
<%= render "shared/footer" %>

app/views/timers/show.html.erb
<%= render "shared/header" %>
<div class="main">
  <div class="show-contents">
    <div class="timer-titles">
      <%@timer_title.zip(@time_count) do |timer_title, time_count|%>
        <div class="timer-title">
          <%= link_to timer_title.timer_title ,new_timer_title_timer_count_path(timer_title.id), class:"timer-title"%>
          <p class="time"><%=time_count%></p>
          <div class="delete-btns">
          <%= link_to "削除する", timer_title_path(timer_title.id), method: :delete, class:"delete-btn"%>
          </div>
        </div>
      <%end%>
    </div>
      <%= link_to "タイマーを作る", new_timer_title_path ,class:"create-timer-title"%>
  </div>
</div>

<%= render "shared/footer" %>